version: '3.9'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
