version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"
    volumes:
      - ./back-end:/app
    networks:
      - backend_network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000"
    volumes:
      - ./front-end:/app
    networks:
      - backend_network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:latest
    ports:
      - "80:80"
    networks:
      - backend_network
    depends_on:
      - front-end
      - back-end

networks:
  backend_network:
    driver: bridge

